### PR TITLE
Use target_has_atomic instead of depending on autocfg

### LINKED ISSUE #32: Atomic::<u32>::is_lock_free() always returns false for ESP32
Hi!

I am experimenting with atomic-rs on an embedded system with an ESP32 mcu using the [esp-idf-hal](https://github.com/esp-rs/esp-idf-hal/) crate with project generated from [esp-idf-template](https://github.com/esp-rs/esp-idf-template).

However I am getting some unexpected results from `Atomic::is_lock_free` which seems to return `false` no matter what I throw at it.

Having a peek at how the cfgs are generated i understand it as the build script looking for `core::sync::atomic::AtomicU32::compare_exchange` being available(for has_atomic_u32). That does work fine in my manuall test below and AtomicU32 is otherwise available and usable.

```rust
use esp_idf_sys as _; // If using the `binstart` feature of `esp-idf-sys`, always keep this module imported

fn main() {
    esp_idf_sys::link_patches(); // Added by esp-rs/esp-idf-template

    std::sync::atomic::AtomicU32::compare_exchange; // Works
    core::sync::atomic::AtomicU32::compare_exchange;// Works

    const _: () = assert!(core::mem::align_of::<u32>() == 4); // Works
    const _: () = assert!(core::mem::size_of::<u32>() == 4); // Works

    // Copy pasted from atomic-rs and commented out cfgs
    pub const fn atomic_is_lock_free<T>() -> bool {
        let size = core::mem::size_of::<T>();
        let align = core::mem::align_of::<T>();
    
        (/*cfg!(has_atomic_u8) & */ (size == 1) & (align >= 1))
            | (/*cfg!(has_atomic_u16) &*/ (size == 2) & (align >= 2))
            | (/*cfg!(has_atomic_u32) &*/ (size == 4) & (align >= 4))
            | (/*cfg!(has_atomic_u64) &*/ (size == 8) & (align >= 8))
            | (/*cfg!(has_atomic_u128) &*/ (size == 16) & (align >= 16))
    }

    const _: () = assert!(atomic_is_lock_free::<u32>()); // Works fine

    const _: () = assert!(atomic::Atomic::<u8>::is_lock_free()); // Does not work
    const _: () = assert!(atomic::Atomic::<u16>::is_lock_free());// Does not work
    const _: () = assert!(atomic::Atomic::<u32>::is_lock_free());// Does not work
    const _: () = assert!(atomic::Atomic::<u64>::is_lock_free());// Does not work
    
    println!("Hello, world!");
}
```

I do have 

```toml
[unstable]
build-std = ["core"]
```

in my project. Could this be https://github.com/cuviper/autocfg/issues/34 ? Is there any solution/work around :) My intention is to use this with my own enum type

### PR DESCRIPTION
**Pull request by usbalbin**
Fixes #32 

This removes the dependency on autocfg, instead using rusts now stabilized [target_has_atomic](https://rust-lang.github.io/rfcs/1543-integer_atomics.html) cfgs.

### CODE REVIEW

File: src/ops.rs [hunk 1]
```diff
@@ -57,31 +57,31 @@ macro_rules! match_atomic {
...
             }
-            #[cfg(has_atomic_i64)]
+            #[cfg(target_has_atomic = "64")]
             8 if mem::align_of::<$type>() >= 8 => {
                 type $atomic = core::sync::atomic::AtomicI64;
 
                 $impl
             }
-            #[cfg(has_atomic_u128)]
+            #[cfg(target_has_atomic = "128")]
```
Comment (Amanieu) [inline src/ops.rs:84]: `AtomicI128` is still unstable, so this should be hidden behind a `"nightly"` feature, otherwise it will cause compile errors on AArch64 (where `target_has_atomic = "128"` is true). You'll also need to enable the `integer_atomics` feature when `"nightly"` is enabled. You can test this with `cargo check --target aarch64-unknown-linux-gnu`.

File: src/lib.rs [hunk 2]
```diff
@@ -33,6 +33,7 @@
 #![warn(missing_docs)]
 #![warn(rust_2018_idioms)]
 #![no_std]
+#![cfg_attr(nightly, feature(integer_atomics))]
```
Comment (Amanieu) [inline src/lib.rs:36]:
```suggestion
#![cfg_attr(feature = "nightly", feature(integer_atomics))]
```

Comment (usbalbin) [reply src/lib.rs]: Oh, thanks

**Comment by usbalbin** [comment]
Anything I can test besides `cargo t` and trying it in my own esp project?

**Comment by usbalbin** [comment]
(I do not have access to a aarch64-unknown-linux-gnu machine)

**Comment by Amanieu** [comment]
Thanks!

**Comment by ds-cbo** [comment]
Thanks for this fix, it seems that this would cut 25 seconds (about 35%) from our compile times. Would it be possible to trigger a new release with this fix on Cargo so that we and others can use a regular version bump instead of relying on the git master branch?

**Comment by Amanieu** [comment]
Done.
